version: '3.8'

services:
  # O serviço da aplicação principal
  api:
    image: ghcr.io/danny-avila/librechat:latest
    ports:
      - "3080:80"
    depends_on:
      - rag_api
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
    environment:
      # Lógica da Aplicação
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION}
      - ALLOW_SOCIAL_LOGIN=${ALLOW_SOCIAL_LOGIN}
      - ALLOW_EMAIL_LOGIN=${ALLOW_EMAIL_LOGIN}
      # Banco de Dados Principal
      - MONGO_URI=${MONGO_URI}
      # Segurança e Tokens
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}
      # OpenAI (para o chat principal)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Auth0
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      # Armazenamento de Arquivos (R2)
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
      - R2_SECRET_KEY=${R2_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE}
      # Comunicação com a RAG API
      - RAG_API_URL="http://rag-api:8000"

  # O serviço da API de RAG para processamento de arquivos
  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    ports:
      - "8000:80"
    environment:
      # OpenAI (para os embeddings dos documentos)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_OPENAI_API_KEY=${RAG_OPENAI_API_KEY}
      # Banco Vetorial (Supabase/PostgreSQL)
      - VECTOR_DB_TYPE=${VECTOR_DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "8000"