version: '3.9'

services:
  rag:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      # OpenAI (embeddings)
      - OPENAI_API_KEY=${RAG_OPENAI_API_KEY}

      # Banco Vetorial (Supabase/PostgreSQL + pgvector)
      - VECTOR_DB_TYPE=${VECTOR_DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      # Armazenamento de Arquivos (R2 / S3)
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
      - R2_SECRET_KEY=${R2_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE}

      # Volume persistente
      - FILE_STORAGE_DIR=${FILE_STORAGE_DIR}

  # ──────────────────────────────────────────────────────
  #  UI / LibreChat Backend
  # ──────────────────────────────────────────────────────
  api:
    image: ghcr.io/danny-avila/librechat:latest
    ports:
      - "3080:3080"
    expose:
      - "3080"
    depends_on:
      - rag
    restart: always
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
    environment:
      # Lógica da Aplicação
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION}
      - ALLOW_SOCIAL_LOGIN=${ALLOW_SOCIAL_LOGIN}
      - ALLOW_EMAIL_LOGIN=${ALLOW_EMAIL_LOGIN}

      # Banco de Dados Principal
      - MONGO_URI=${MONGO_URI}

      # Segurança e Tokens
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}

      # OpenAI (chat principal)
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      # OpenID Connect (Auth0)
      - OPENID_CLIENT_ID=${OPENID_CLIENT_ID}
      - OPENID_CLIENT_SECRET=${OPENID_CLIENT_SECRET}
      - OPENID_ISSUER=${OPENID_ISSUER}
      - OPENID_AUTHORIZATION_URL=${OPENID_AUTHORIZATION_URL}
      - OPENID_TOKEN_URL=${OPENID_TOKEN_URL}
      - OPENID_USERINFO_URL=${OPENID_USERINFO_URL}
      - OPENID_SCOPE=${OPENID_SCOPE}
      - OPENID_CALLBACK_URL=${OPENID_CALLBACK_URL}

      # Armazenamento de Arquivos (R2 / S3)
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
      - R2_SECRET_KEY=${R2_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE}

      # Comunicação interna com a RAG API
      - RAG_API_URL=http://rag:8000

      # Volume persistente
      - FILE_STORAGE_DIR=${FILE_STORAGE_DIR}
